mysql:
  namespace: mysql
  secrets:
    MYSQL_ROOT_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
    MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
    MYSQL_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
  statefulSet:
    replicas: 1
  image:
    repository: mysql
    tag: 8.0
  pvc:
    volumeName: mysql-pv-data
    accessModes: ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  affinity:
    nodeAffinity:
      matchExpressions:
        key: "app"
        operator: In
        values: mysql
    podAffinity:
      matchExpressions:
        key: "app"
        operator: In
        values: mysql
  tolerations:
    key: "app"
    operator: "Equal"
    value: "mysql"
    effect: "NoSchedule"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "100m"