apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.todoapp.namespace }}
spec:
  strategy:
    type: {{ .Values.todoapp.stratagy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.todoapp.stratagy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.todoapp.stratagy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.todoapp.serviceAccountName }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.todoapp.image.repository }}:{{ .Values.todoapp.image.tag }}
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: app-secrets-volume
          mountPath: "/app/secrets"
          readOnly: true
        - name: app-config-volume
          mountPath: "/app/configs"
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.todoapp.requests.memory }}
            cpu: {{ .Values.todoapp.requests.cpu }}
          limits:
            memory: {{ .Values.todoapp.limits.memory }}
            cpu: {{ .Values.todoapp.limits.cpu }}
        env:
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: PYTHONUNBUFFERED
        {{- range $key, $value := .Values.todoapp.secrets.data }}
        - name: {{ $key }}
          value: {{ $value | b64dec | quote }}
        {{- end }}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-pv-data
      - name: app-secrets-volume
        secret:
          secretName: {{ .Chart.Name }}-secret
      - name: app-config-volume
        configMap:
          name: {{ .Chart.Name }}-config
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: {{ .Values.todoapp.affinity.nodeAffinity.matchExpressions.key }}
                operator: {{ .Values.todoapp.affinity.nodeAffinity.matchExpressions.operator }}
                values:
                - {{ .Values.todoapp.affinity.nodeAffinity.matchExpressions.values }}